# Activate with SPRING_PROFILES_ACTIVE=prod or --spring.profiles.active=prod
server.ssl.enabled=${SSL_ENABLED:true}
server.port=${SERVER_PORT:443}
server.ssl.key-store=${SSL_KEY_STORE:classpath:keystore.p12}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}

selenium.chrome.arguments=${SELENIUM_CHROME_ARGUMENTS:--no-sandbox,--headless,--window-size=1024x768}
